// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlhrcamtvbbqwghfscxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsaHJjYW10dmJicXdnaGZzY3hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NTYxNzIsImV4cCI6MjA2MzEzMjE3Mn0.ADili2jSM6_c-rdu3gx7zLvKU1jYukBMBZkPBFyGhmg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);